# Generated by Django 3.1.3 on 2020-11-11 17:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_doors', models.IntegerField(default=24)),
                ('start_date', models.DateField(default=datetime.date(2020, 12, 1))),
                ('slug', models.SlugField()),
                ('theme', models.CharField(choices=[('PL', 'Plain'), ('RE', 'Red with snowflakes'), ('CU', 'Cupcakes and candy'), ('TR', 'Christmas trees'), ('TW', 'Twigs'), ('SN', 'Snowmen')], default='PL', max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('content', models.TextField(max_length=1000)),
                ('opening_date', models.DateField(default=django.utils.timezone.now)),
                ('open', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('slug', models.SlugField()),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventcalendar.calendar')),
            ],
        ),
    ]
