# Generated by Django 2.2.16 on 2020-10-22 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adventcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='door',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
