# Generated by Django 3.1.3 on 2020-11-21 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventcalendar', '0002_auto_20201121_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 12, 1), help_text='(Format: YY-MM-DD)'),
        ),
    ]
