# Generated by Django 3.1.3 on 2020-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventcalendar', '0005_calendar_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='theme',
            field=models.CharField(choices=[('CU', 'Cupcakes and Candy'), ('TR', 'Christmas Trees')], default='CU', max_length=2),
        ),
    ]
