# Generated by Django 3.1.3 on 2020-11-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventcalendar', '0006_calendar_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='theme',
            field=models.CharField(choices=[('PL', 'Plain'), ('CU', 'Cupcakes and candy'), ('TR', 'Christmas trees'), ('HA', 'Hare in the snow')], default='PL', max_length=2),
        ),
    ]
