# Generated by Django 3.1.3 on 2020-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventcalendar', '0007_auto_20201106_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='theme',
            field=models.CharField(choices=[('PL', 'Plain'), ('RE', 'Red with snowflakes'), ('CU', 'Cupcakes and candy'), ('TR', 'Christmas trees'), ('TW', 'Twigs'), ('SN', 'Snowmen')], default='PL', max_length=2),
        ),
    ]
