# Generated by Django 3.1.3 on 2020-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventcalendar', '0008_auto_20201107_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
